{% set name = "python-cas" %}
{% set version = "1.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8df85add9a02a02f33270642ba1e5b2e319c340a30bd00741011584beb2282fa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - lxml
    - python >=3.6
    - requests
    - six

test:
  imports:
    - cas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-cas/python-cas
  summary: Python CAS client library
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mxr-conda
